;AI套皮单位
[VehicleTypes]
+=FVE1
+=FVGGI
+=FVGHOST
+=CFVFK
+=CFVPLAFK
+=HTNKAI
+=HTKSHK
+=HARVAI
+=HTKDRON
+=HTKIVAN
+=HTKDESO
+=HTKTERROR
+=CASDEAI
+=CV3AI
+=V3AI
+=CHARAI
+=CLTNKAI
+=TSLAI
+=CAPOCAI
+=APOCXE
+=HYDAI
+=SUBAI
+=DREDAI
+=SQDAI
+=AN255APOC
+=CrainGunAI
+=CDREDAI
+=CHYDAE
+=CARRIERAI
+=DESTAI
+=AEGISAI
+=DLPHAI

[FVE1]:[FV]
Image=FV
Prerequisite=BUFFACOD
InitialPayload.Types=E1
InitialPayload.Nums=1
CrateGoodie=no
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[FVGGI]:[FV]
Image=FV
Prerequisite=BUFFACOD
InitialPayload.Types=GGI
InitialPayload.Nums=1
CrateGoodie=no
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[FVGHOST]:[FV]
Image=FV
Prerequisite=BUFFACOD
InitialPayload.Types=GHOST
InitialPayload.Nums=1
CrateGoodie=no
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.5

[CFVFK]:[CFV]
UIName=Name:FV
Name=China IFV
Image=CGGY
Prerequisite=BUFFACOD
NoManualFire=yes
NoManualEnter=yes
BuildTimeMultiplier=0.01

[CFVPLAFK]:[CFV]
UIName=Name:FV
Name=China IFV
Image=CGGY
Prerequisite=BUFFACOD
InitialPayload.Types=PLAFK
InitialPayload.Nums=1
NoManualFire=yes
NoManualEnter=yes
BuildTimeMultiplier=0.01

[HTNKAI]:[HTNK]
Image=HTNK
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
NoManualFire=yes
BuildTimeMultiplier=0.2
Prerequisite.Negative=NATECH
Primary=121mm
ElitePrimary=121mmE

[121mm]:[120mm]
Range=5.75
MinimumRange=5

[121mmE]:[120mm]
Range=5.75
MinimumRange=5

[HTKSHK]:[HTK]
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=HTK
Passengers=9
InitialPayload.Types=SHK,DRON
InitialPayload.Nums=5,2
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[HTKDRON]:[HTK]
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=HTK
Passengers=10
InitialPayload.Types=DRON
InitialPayload.Nums=5
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[HTKIVAN]:[HTK]
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=HTK
Passengers=5
InitialPayload.Types=IVAN
InitialPayload.Nums=5
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[HTKDESO]:[HTK]
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=HTK
Passengers=5
InitialPayload.Types=DESO
InitialPayload.Nums=5
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[HTKTERROR]:[HTK]
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=HTK
Passengers=5
InitialPayload.Types=TERROR
InitialPayload.Nums=5
NoManualFire=yes
NoManualUnload=yes
BuildTimeMultiplier=0.2

[HARVAI]:[HTNK]
Image=HARV
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
NoManualFire=yes
NoManualMove=yes
BuildTimeMultiplier=0.2
AllowedToStartInMultiplayer=no
Cost=1400
Speed=7
Strength=2000
Primary=20mmRapid
ElitePrimary=20mmRapidE
ImmuneToVeins=yes
ImmuneToPsionics=yes
ImmuneToRadiation=yes

[CASDEAI]:[CASDE]
UIName=Name:CASDE
Name=Kirov Airship
Image=CASDE
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
BuildTimeMultiplier=0.1
NoManualFire=yes
NoManualMove=yes

[CV3AI]:[CV3]
UIName=Name:CV3
Name=China V3 Launcher
Image=CV3
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
BuildTimeMultiplier=0.1
NoManualFire=yes

[V3AI]:[V3]
UIName=Name:V3
Name=V3 Launcher
Image=V3
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
BuildTimeMultiplier=0.1
NoManualFire=yes

[CHARAI]:[CHAR]
UIName=Name:CHAR
Image=CHAR
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
BuildTimeMultiplier=0.5
NoManualMove=yes

[CLTNKAI]:[CLTNK]
UIName=Name:LTNK
Name=China Light Tank
Image=CLTNK
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Prerequisite.Negative=CATECHA
BuildTimeMultiplier=0.5
NoManualFire=yes

[TSLAI]:[TSL]
UIName=Name:TSL
Name=Tesla Tank
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Image=TSL
BuildTimeMultiplier=0.2
NoManualFire=yes

[CAPOCAI]:[CAPOC]
UIName=Name:APOC
Name=中国T3天启坦克
Image=CAPOC
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
Primary=APOC156mmx
ElitePrimary=APOC156mmxE

[APOC156mmx]:[APOC155mmx]
Range=6
MinimumRange=5

[APOC156mmxE]:[APOC155mmxE]
Range=7
MinimumRange=6

[APOCXE]:[APOCX]
UIName=Name:APOCX
Image=APOCX
Strength=4000
Prerequisite=NAWEAP,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
BuildTimeMultiplier=0.2
Passengers=3
InitialPayload.Types=PLAFK
InitialPayload.Nums=3
SizeLimit=2
UIDescription=Name:APOCXtip

[HYDAI]:[HYD]
UIName=Name:HYD
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
Image=HYD
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[DREDAI]:[DRED]
UIName=Name:DRED
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
Image=DRED
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[SUBAI]:[SUB]
UIName=Name:SUB
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
Image=SUB
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[SQDAI]:[SQD]
UIName=Name:SQD
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
Image=HYD
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[AN255APOC]:[AN255]
UIName=Name:AN255
Image=AN255
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
Name=安255超级运输机
Primary=M60
NoManualUnload=yes
Ammo=1
Reload=99999999
DeployToFire=yes
Insignificant=yes
InitialPayload.Types=APOC,SHK,SMCV,ZEP,HTK,DRON
InitialPayload.Nums=20,20,6,10,20,20
BuildTimeMultiplier=0.2

[CrainGunAI]:[CrainGun]
UIName=Name:TrainGun
Image=TrainGun
Prerequisite=NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[CDREDAI]:[CDRED]
UIName=Name:DRED
Name=China Dreadnought
Image=CDRED
Prerequisite=CAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[CHYDAE]:[CHYDA]
UIName=Name:CHYDA
Name=China Dreadnought
Image=CHYDA
Prerequisite=CAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[CARRIERAI]:[CARRIER]
UIName=Name:CARRIER
Name=Aircraft Carrier
Image=CARRIER
Prerequisite=GAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[DESTAI]:[DEST]
UIName=Name:DEST
Name=Aircraft Carrier
Image=DEST
Prerequisite=GAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[AEGISAI]:[AEGIS]
UIName=Name:AEGIS
Name=Aircraft Carrier
Image=AEGIS
Prerequisite=GAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[DLPHAI]:[DLPH]
UIName=Name:DLPH
Name=Aircraft Carrier
Image=DLPH
Prerequisite=GAYARD,NAYARD,CALAB,CASLAB,NAMISL,DMTK
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2

[AircraftTypes]
+=J10AI

[J10AI]:[J10]
UIName=Name:J10
Name=Black Eagle
Image=J10
Prerequisite=CARADR,DMTK,CALAB,CASLAB
NoManualMove=yes
NoManualFire=yes
BuildTimeMultiplier=0.2
Dock=CARADRA,CARADRB,CARADRC

[BuildingTypes]
+=CTESLAAI
+=CSAMAI
+=YAGGUNAI
+=ATESLAAI
+=NASAMAI
+=NALASRAI
+=TESLAAI

[CTESLAAI]:[CTESLA]
UIName=Name:CTESLA
Name=光棱塔
Image=CAPRIS
TechLevel=11
Prerequisite=CATECHE
Strength=400
Power=-1

[CSAMAI]:[CSAM]
UIName=Name:CSAM
Name=China Patriot Missile
Image=CSAM
TechLevel=11
Prerequisite=CATECHE
Strength=600
Power=-2

[YAGGUNAI]:[YAGGUN]
UIName=Name:GattCannon
Name=Yuri Gattling Cannon
BuildCat=Combat
Image=YAGGUN
TechLevel=11
Strength=810
Prerequisite=YAWEAP4
Adjacent=6
Power=-2


[ATESLAAI]:[ATESLA]
UIName=Name:ATESLA
Prerequisite=GAGAPA
Image=GAPRIS
TechLevel=11
Strength=300
AIBuildThis=no
Power=-2

[NASAMAI]:[NASAM]
UIName=Name:NASAM
Prerequisite=GAGAPA
TechLevel=11
Image=NASAM
Strength=300
AIBuildThis=no
Power=-2

[NALASRAI]:[NALASR]
Image=NALASR
TechLevel=11
Adjacent=6
AIBuildThis=no
Prerequisite=NATECHD

[TESLAAI]:[TESLA]
UIName=Name:TESLA
Name=磁暴线圈
Image=NATSLA
TechLevel=11
Prerequisite=NATECHD
Power=2




