[GlobalControls]
DebugKeysEnabled=yes
AllowBypassBuildLimit=no,no,no
AllowParallelAIQueues=yes
;ForbidParallelAIQueues.Infantry=yes 
;ForbidParallelAIQueues.Vehicle=yes 
;ForbidParallelAIQueues.Navy=yes
;ForbidParallelAIQueues.Aircraft=yes 
ForbidParallelAIQueues.Building=no 

[GAWEAP2]
AIBuildCounts=2,2,1

[GAWEAP3]
AIBuildCounts=3,2,1

[GAAIRC2]
AIBuildCounts=2,2,1
AIExtraCounts=3,2,2
AIBuildThis=yes

[GAAIRC3]
AIBuildThis=yes

[NAWEAP2]
AIBuildCounts=2,2,1

[NAWEAP3]
AIBuildCounts=3,2,1

[YAWEAP2]
AIBuildCounts=2,2,1

[YAWEAP3]
AIBuildCounts=3,2,1

[CAWEAP2]
AIBuildCounts=2,2,1

[CAWEAP3]
AIBuildCounts=3,2,1

[CARADR2]
AIBuildCounts=2,2,1
AIExtraCounts=3,2,2
AIBuildThis=yes

