[Themes]
; 主题配置格式：序号=主题显示名称,主题资源文件夹名\
0=Default,ThemeDefault/

[Voice]
0=官方,Resources/Voice/官方/
1=问天,Resources/Voice/问天/

[Settings]
WindowTitle=新共和国之辉 1.3.1

; 游戏完整名称，将在客户端各类UI界面中显示
LongGameName=YR Mod

; 本地游戏唯一标识，与ClientCore核心库的游戏定义一一对应
LocalGame=GH

; CnCNet联机平台在线状态识别唯一ID
CnCNetLiveStatusIdentifier=

; 当DirectX11初始化失败、客户端生成.dxfail故障文件后，启动的备用程序
LauncherExe=YRLauncher.exe

; 游戏主程序可执行文件名
; 支持英文逗号分隔填写多个名称，但当前程序仅识别第一个参数
GameExecutableNames=gamemd.exe

GameLauncherExecutableName=syringe.exe

; Linux/Mac系统专用的游戏启动脚本文件名
UnixGameExecutableName=Resources/Compatibility/Unix/wine-game.sh

; 游戏启动附加命令行参数（按需取消注释填写内容）
ExtraCommandLineParams=-LOG -CD -speedcontrol

; 客户端与游戏通用的核心配置文件名称
SettingsFile=RA2MD.ini

; 游戏快捷键配置文件，对应客户端设置界面的按键自定义功能
KeyboardINI=KeyboardMD.ini

; 对局结束后，用于统计、读取对战数据的日志文件名称
StatisticsLogFileName=debug/debug.log

; 多人联机地图定义配置文件路径
MPMapsPath=INI/MPMaps.ini

; 地图编辑器启动批处理文件路径
MapEditorExePath=FinalAlert2SP/RunFA2Ext.bat

UnixMapEditorExePath=Resources/Compatibility/Unix/wine-mapedit.sh

; FinalSun地图编辑器配置文件路径，客户端会自动写入当前游戏安装目录
FSIniPath=FinalAlert2SP/FinalAlert.ini

; 战役拓展配置文件名，存放于INI目录下
; 官方建议优先将所有战役数据写入Battle.ini，而非此文件
BattleFSFileName=

RequiredFiles=

ForbiddenFiles=

; 客户端附加菜单中「制作人员名单」的跳转链接
CreditsURL=

; 客户端更新弹窗中「更新日志」的跳转链接
ChangelogURL=

; 客户端崩溃、更新失败时展示的官方支持论坛完整链接
LongSupportURL=

; 简化版官方支持论坛链接，用于弹窗简短展示
ShortSupportURL=

; 游戏中每个阵营对应的加载界面图片数量
LoadingScreenCount=0

MaxNameLength=16

; 客户端窗口最小渲染宽度，低于该分辨率将自动缩小画面渲染
MinimumRenderWidth=1280

; 客户端窗口最小渲染高度，低于该分辨率将自动缩小画面渲染
MinimumRenderHeight=768

; 客户端窗口最大渲染宽度，超出该分辨率仅对画面进行放大适配
MaximumRenderWidth=1366 ;1280

; 客户端窗口最大渲染高度，超出该分辨率仅对画面进行放大适配
MaximumRenderHeight=800

MinimumIngameWidth=800

MinimumIngameHeight=600

MapCellSizeX=60

MapCellSizeY=30

; 游戏启动时是否自动在spawn.ini中写入SidebarHack=true（高分辨率侧边栏错位修复）
SidebarHack=no

CopyMissionsToSpawnmapINI=no

UseBuiltStatistic=yes

CreateSavedGamesDirectory=yes

SaveSkirmishGameOptions=yes

DisableMultiplayerGameLoading=yes

DisplayPlayerCountInTopBar=no

; 允许自定义地图生效的所有游戏模式
AllowedCustomGameModes=Standard,Team Alliance,Megawealth,Land Rush,Meat Grinder,Naval War,Cooperative

UseClientRandomStartLocations=no

; Discord社交状态绑定ID，用于展示游戏在线游玩状态
DiscordAppId=

; 注释掉此行可关闭模组模式、开启客户端自动更新功能
ModMode=true