; List of custom CnCNet games / mods.
[CustomGames]
0=CustomGame

[CustomGame]
InternalName=GH
UIName=Glory of the republic
ChatChannel=#cncnet-gh
GameBroadcastChannel=#cncnet-gh-games
ClientExecutableName=YRLauncher.exe
RegistryInstallPath=HKLM\Software\CustomGame
IconFilename=customgameicon.png
