[INISystem]
BasedOn=GenericWindow.ini

[SkirmishLobby]
PlayerOptionLocationX=12
PlayerOptionLocationY=25	    ; def=24
PlayerOptionVerticalMargin=9	; def=12
PlayerOptionHorizontalMargin=5	; def=3
PlayerOptionCaptionLocationY=6	; def=6
PlayerStatusIndicatorX=8
PlayerStatusIndicatorY=0
PlayerNameWidth=100             ; def=136
SideWidth=110	                ; def=91
ColorWidth=80	                ; def=79
StartWidth=45	                ; def=49
TeamWidth=35	                ; def=46

; controls
$CC00=btnLaunchGame:GameLaunchButton
$CC01=btnLeaveGame:XNAClientButton
$CC03=MapPreviewBox:MapPreviewBox
$CC04=ChkOptionsPanel:XNAPanel
$CC05=PlayerOptionsPanel:XNAPanel
$CC06=lblMapName:XNALabel
$CC07=lblMapAuthor:XNALabel
$CC08=lblGameMode:XNALabel
$CC09=lblMapSize:XNALabel
$CC12=lbMapList:XNAMultiColumnListBox
$CC13=ddGameMode:XNAClientDropDown
$CC14=lblGameModeSelect:XNALabel
$CC15=btnPickRandomMap:XNAClientButton
$CC16=tbMapSearch:XNASuggestionTextBox
$CC17=PlayerExtraOptionsPanel:PlayerExtraOptionsPanel
$CC18=lbChatMessages:ChatListBox
$CC19=tbChatInput:XNAChatTextBox
$CC20=panelBorderTop:XNAExtraPanel
$CC21=panelBorderBottom:XNAExtraPanel
$CC22=panelBorderLeft:XNAExtraPanel
$CC23=panelBorderRight:XNAExtraPanel
$CC24=panelBorderCornerTL:XNAExtraPanel
$CC25=panelBorderCornerTR:XNAExtraPanel
$CC26=panelBorderCornerBL:XNAExtraPanel
$CC27=panelBorderCornerBR:XNAExtraPanel
$CC28=CmbOptionsPanel:XNAPanel

[lblName]
Text=玩家

[lblSide]
Text=国家

[lblStart]
Text=位置
Visible=true

[lblColor]
Text=颜色

[lblTeam]
Text=小队

[ddPlayerStartBase]
Enabled=true
Visible=true

[ddPlayerStart0]
$BaseSection=ddPlayerStartBase

[ddPlayerStart1]
$BaseSection=ddPlayerStartBase

[ddPlayerStart2]
$BaseSection=ddPlayerStartBase

[ddPlayerStart3]
$BaseSection=ddPlayerStartBase

[ddPlayerStart4]
$BaseSection=ddPlayerStartBase

[ddPlayerStart5]
$BaseSection=ddPlayerStartBase

[ddPlayerStart6]
$BaseSection=ddPlayerStartBase

[ddPlayerStart7]
$BaseSection=ddPlayerStartBase

[lbMapList]
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=EMPTY_SPACE_TOP + 93
$Width=300
$Height=565
SolidColorBackgroundTexture=0,0,0,128

[ddGameMode]
$Width=150
$Height=DEFAULT_CONTROL_HEIGHT
$X=getRight(lbMapList) - getWidth($Self)
;$Y=getY(lbMapList) - getHeight($Self) - EMPTY_SPACE_TOP -20
$Y=getY(PlayerOptionsPanel) +10

[lblGameModeSelect]
Text=游戏模式：
$Text=GameMode
$X=getX(ddGameMode) - getWidth($Self) - LABEL_SPACING
$Y=getY(ddGameMode) + 5

[btnMapSortAlphabetically]
Visible=false
Enabled=false

[lblModeText]
$X=getX(lblGameModeSelect)
$Y=getY(lblGameModeSelect) + 25

[btnLaunchGame]
Text=开始游戏
$Text=LaunchGame
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getHeight($ParentControl) - getHeight($Self) - EMPTY_SPACE_BOTTOM

[btnPickRandomMap]
Text=选择随机地图
$Text=PickRandomMap
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getY(btnLaunchGame) - getHeight($Self) - LOBBY_PANEL_SPACING

[tbMapSearch]
$Width=getRight(lbMapList) - getRight(btnPickRandomMap) - LOBBY_PANEL_SPACING
$Height=DEFAULT_BUTTON_HEIGHT ;DEFAULT_CONTROL_HEIGHT
$X=getRight(btnPickRandomMap) + LOBBY_PANEL_SPACING
$Y=getY(btnPickRandomMap) ; + 1
BackColor=255,255,255
;SolidColorBackgroundTexture=0,0,0,128

[btnAginLoadMaps]
Text = Refresh list
$Text = RefreshList
$X=10
$Y=25

[btnRandomMap]
Text = Generate map
$Text = GenerateMap
$X=getX(btnLaunchGame) + 150
$Y=getY(btnLaunchGame)


[MapPreviewBox]
$Width=800
$Height=423
$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES -150
$Y=280

SolidColorBackgroundTexture=0,0,0,128

[lblMapName]
$Height=DEFAULT_LBL_HEIGHT
$X=getX(MapPreviewBox)
$Y=getBottom(MapPreviewBox) + LABEL_SPACING

[lblMapAuthor]
$TextAnchor=LEFT
$AnchorPoint=getRight(MapPreviewBox),getY(lblMapName)

[lblGameMode]
$Height=DEFAULT_LBL_HEIGHT
$X=getX(lblMapName)
$Y=getBottom(lblMapName) + LABEL_SPACING

[lblMapSize]
$Height=DEFAULT_LBL_HEIGHT
$X=getX(lblGameMode)
$Y=getBottom(lblGameMode) + LABEL_SPACING

[btnLeaveGame]
Text=离开游戏
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES
$Y=getY(btnLaunchGame)

[PlayerOptionsPanel]
$X=getX(ChkOptionsPanel) - 420
$Y=EMPTY_SPACE_TOP
;$Width=getWidth($ParentControl) - (getX($Self) + (getWidth(ChkOptionsPanel) + LOBBY_EMPTY_SPACE_SIDES + LOBBY_PANEL_SPACING)
$Width=413
$Height=getHeight(ChkOptionsPanel)
SolidColorBackgroundTexture=0,0,0,128

$CC00=btnPlayerExtraOptionsOpen:XNAClientButton

[PlayerExtraOptionsPanel]
$Width=238
$Height=247
$X=getRight(PlayerOptionsPanel) - getWidth($Self)
$Y=getY(PlayerOptionsPanel)
SolidColorBackgroundTexture=0,0,0,128

[btnPlayerExtraOptionsOpen]
$Width=OPEN_BUTTON_WIDTH
$Height=OPEN_BUTTON_HEIGHT
$X=getWidth($ParentControl) - getWidth($Self)
$Y=0
IdleTexture=optionsButton.png
HoverTexture=optionsButton_c.png

[ChkOptionsPanel]
$Width=380
$Height=265
;$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES
$X=getWidth($ParentControl) - 543
$Y=EMPTY_SPACE_TOP
SolidColorBackgroundTexture=0,0,0,128

[CmbOptionsPanel]
$Width=145
$Height=getHeight(MapPreviewBox) + getHeight(PlayerOptionsPanel)+5
$X=getWidth(MapPreviewBox) + getX(MapPreviewBox) +10
$Y=getY(PlayerOptionsPanel)
SolidColorBackgroundTexture=0,0,0,128

; 1 column checkboxes
$CC-GO01=chkShortGame:GameLobbyCheckBox
$CC-GO02=chkRedeplMCV:GameLobbyCheckBox
;$CC-GO03=
$CC-GO04=chkCrates:GameLobbyCheckBox
$CC-GO05=chkBuildOffAlly:GameLobbyCheckBox
$CC-GO06=chkMultiEngineer:GameLobbyCheckBox
;一键三星
$CC-GO07=chkThreeStarUnits:GameLobbyCheckBox

; 2 column checkboxes
$CC-GO08=chkIngameAllying:GameLobbyCheckBox
$CC-GO09=chkStolenTech:GameLobbyCheckBox
;科技建筑无敌
$CC-GO010=chkImmuneDerricks:GameLobbyCheckBox
$CC-GO011=chkDestroyableBridges:GameLobbyCheckBox
$CC-GO013=chkNoSpawnPreview:GameLobbyCheckBox
$CC-GO014=chkSatellite:GameLobbyCheckBox


; three Column of Checkboxes
$CC-GO015=chkFreeRadar:GameLobbyCheckBox
$CC-GO016=chkConYardStart:GameLobbyCheckBox
;多工厂加速
$CC-GO017=chkMutiFactory:GameLobbyCheckBox
$CC-GO018=chkAutoRepair:GameLobbyCheckBox
$CC-GO019=chkFogOfWar:GameLobbyCheckBox
;疯狂矿石精炼
$CC-GO020=chkHugeWealthy:GameLobbyCheckBox
$CC-GO021=chkTech:GameLobbyCheckBox
;$CC-GO022=
$CC-GO023=chkTech2:GameLobbyCheckBox
$CC-GO024=chkBuildLimit:GameLobbyCheckBox
$CC-GO025=chkAILimit:GameLobbyCheckBox
;疯狂箱子
$CC-GO026=chkCrazyBox:GameLobbyCheckBox
;铜墙铁壁
$CC-GO027=chkStrenghBuild:GameLobbyCheckBox
;赏金猎人模式
$CC-GO028=chkBountyHunter:GameLobbyCheckBox
;中立建筑归还
$CC-GO029=chkReturnBuilding:GameLobbyCheckBox
;清除废墟，使得能够在其场地上新建建筑
$CC-GO030=chkRemoveRubble:GameLobbyCheckBox

;针对防守地图：是否启用原生Ai
$CC-GO050=chkDefenceAiTrigger:GameLobbyCheckBox
; Dropdowns

$CC-GODD01=lblGame:XNALabel
$CC-GODD02=cmbGame:GameLobbyDropDown
$CC-GODD03=lblCredits:XNALabel
$CC-GODD04=cmbCredits:GameLobbyDropDown
$CC-GODD05=lblGameSpeedCap:XNALabel
$CC-GODD06=cmbSkirmishGameSpeedCap:GameLobbyDropDown
$CC-GODD07=lblStartingUnits:XNALabel
$CC-GODD08=cmbStartingUnits:GameLobbyDropDown
$CC-GODD09=lblTime:XNALabel
$CC-GODD010=cmbTime:GameLobbyDropDown
$CC-GODD011=lblAI:XNALabel
$CC-GODD012=cmbAI:GameLobbyDropDown
$CC-GODD013=lblOreGrowth:XNALabel
$CC-GODD014=cmbOreGrowth:GameLobbyDropDown
$CC-GODD015=lblTechLevel:XNALabel
$CC-GODD016=cmbTechLevel:GameLobbyDropDown
$CC-GODD017=lblSw:XNALabel
$CC-GODD018=cmbSw:GameLobbyDropDown
$CC01=BtnSaveLoadGameOptions:XNAClientButton

[BtnSaveLoadGameOptions]
$Width=OPEN_BUTTON_WIDTH
$Height=OPEN_BUTTON_HEIGHT
$X=getWidth($ParentControl) - getWidth($Self)
$Y=0
IdleTexture=optionsButton.png
HoverTexture=optionsButton_c.png

;============================
; LEFT Column Checkboxes
;============================

[lblCredits]
Text=初始资金
$X = EMPTY_SPACE_SIDES + 7
$Y = EMPTY_SPACE_TOP

[cmbCredits]
OptionName=cmbCredits
Items=500000,250000,100000,50000,30000,20000,15000,10000,7500,5000
DefaultIndex=7
SpawnIniOption=Credits
DataWriteMode=String
$X = getX(lblCredits)
$Y = getY(lblCredits) + 30
Size=110,23

[lblGameSpeedCap]
Text=游戏速度：
$X = getX(lblCredits)
$Y = getY(lblCredits) + 70

[cmbSkirmishGameSpeedCap]
OptionName=cmbGameSpeed
Items=6 最快,5 很快,4 快,3 中等,2 慢,1 很慢,0 最慢
DefaultIndex=1
SpawnIniOption=GameSpeed
DataWriteMode=Index
$X = getX(lblCredits)
$Y = getY(lblGameSpeedCap) + 30
Size=110,23

[lblStartingUnits]
Text=初始部队
$X = getX(lblCredits)
$Y = getY(lblGameSpeedCap) + 70

[cmbStartingUnits]
OptionName=cmbStartingUnits
Items=10,9,8,7,6,5,4,3,2,1,0
DefaultIndex=10
SpawnIniOption=UnitCount
DataWriteMode=String
$X = getX(lblCredits)
$Y = getY(lblStartingUnits) + 30
Size=110,23
ControlName=chkTech,chkTech,chkTech,chkTech,chkTech,chkTech,chkTech,chkTech,chkTech,chkTech,
ControlIndex=0,0,0,0,0,0,0,0,0,0,

[lblTime]
Text=时间
$X = getX(lblCredits)
$Y = getY(lblStartingUnits) + 70

[cmbTime]
OptionName=cmbTime
Items=,INI\Game Options\Time\Morning.ini,INI\Game Options\Time\Day.ini,INI\Game Options\Time\Dusk.ini,INI\Game Options\Time\Night.ini,INI\Game Options\Time\Rain.ini,INI\Game Options\Time\Snow.ini
ItemLabels=默认,凌晨,中午,黄昏,夜晚,雨天,雪天
DefaultIndex=0
DataWriteMode=MapCode
$X = getX(lblCredits)
$Y = getY(lblTime) + 30
Size=110,23

[lblAI]
Text=内置AI
$X = getX(lblCredits)
$Y = getY(lblTime) + 70

[cmbAI]
OptionName=cmbAI
Mod = true
; 不要恢复下面的代码。
;Items=INI\Game Options\AI\Other,INI\Game Options\
;ItemLabels=标准,AI平行生产
DataWriteMode=MapCode
DefaultIndex=0
$X = getX(lblCredits)
$Y = getY(lblAI) + 30
Size=110,23
;ControlName=,,,,cmbGame
;ControlIndex=,,,,0



[lblOreGrowth]
Text = 矿石生长
$X = getX(lblCredits)
$Y = getY(lblAI) + 70

[cmbOreGrowth]
OptionName=cmbOreGrowth
Items=INI\Game Options\ore\OreStandard.ini,INI\Game Options\ore\OreDouble.ini,INI\Game Options\ore\OreSpread.ini,INI\Game Options\ore\OreGrowth.ini
ItemLabels=标准,双倍,最小,无
DataWriteMode=MapCode
DefaultIndex=0
$X = getX(lblCredits)
$Y = getY(lblOreGrowth) + 30
Size=110,23
ToolTip=Adjusted the ore growth and spread rate in the game

[lblTechLevel]
Text=科技等级
$X = getX(lblCredits)
$Y = getY(lblOreGrowth) + 70

[cmbTechLevel]
OptionName=StartingUnits
Items=10,9,8,7,6,5,4,3,2,1
DefaultIndex=0
SpawnIniOption=TechLevel
DataWriteMode=String
$X = getX(lblCredits)
$Y = getY(lblTechLevel) + 30
Size=110,23

[lblSw]
Text=超级武器
$X = getX(lblCredits)
$Y = getY(lblTechLevel) + 70

[cmbSw]
OptionName=cmbSw
Items = INI\Game Options\Sw\disable.ini,INI\Game Options\Sw\support.ini,INI\Game Options\Sw\all.ini
ItemLabels = 全部禁用,开启小超武,全部开启
DataWriteMode=MapCode
DefaultIndex= 2
$X = getX(lblCredits)
$Y = getY(lblSw) + 30
Size=110,23

;============================
; 1 Column of Checkboxes
;============================

[chkShortGame]
Text=快速游戏
SpawnIniOption=ShortGame
Checked=True
$X = EMPTY_SPACE_SIDES
$Y = 10
$Parent = ChkOptionsPanel
ToolTip=推毁所有建筑即可获得胜利！

[chkRedeplMCV]
Text = 基地重新部署
SpawnIniOption=MCVRedeploy
Checked=True
$X=getX(chkShortGame)
$Y=getY(chkShortGame)+25
$Parent = ChkOptionsPanel
ToolTip = 基地可还原为基地车并选择位置重新部署！

[chkCrates]
Text= 随机工具箱
SpawnIniOption=Crates
Checked=True
$X=getX(chkRedeplMCV)
$Y=getY(chkRedeplMCV)+25
$Parent = ChkOptionsPanel
ToolTip= 出现随机工具箱！

[chkBuildOffAlly]
Text = 盟友旁建设
SpawnIniOption=BuildOffAlly
Checked=True
$X=getX(chkCrates)
$Y=getY(chkCrates)+25
$Parent = ChkOptionsPanel
ToolTip = 可以在盟友基地旁边建立自己的建筑！

[chkMultiEngineer]
Text = 多位工程师
SpawnIniOption=MultiEngineer
$X=getX(chkBuildOffAlly)
$Y=getY(chkBuildOffAlly)+25
$Parent = ChkOptionsPanel
ToolTip=需要三个工程师才可以占领建筑！

[chkThreeStarUnits]
Text= 一键三星
SpawnIniOption=Diurnal
CustomIniPath=INI/Game Options/ThreeStarUnits.ini
Checked=False
$X=getX(chkMultiEngineer)
$Y=getY(chkMultiEngineer)+25
$Parent = ChkOptionsPanel
ToolTip= 敌我方生产的所有单位均为三星！

[chkIngameAllying]
Text= 游戏中解结盟
SpawnIniOption=AlliesAllowed
CustomIniPath=INI/Game Options/AlliesAllowed.ini
Checked=True
$X=getX(chkThreeStarUnits)
$Y=getY(chkThreeStarUnits)+25
$Parent = ChkOptionsPanel
ToolTip= 允许游戏内变更盟友！

[chkStolenTech]
Text= AI平行生产
CustomIniPath=INI/Game Options/AI平行生产.ini
Checked=True
$X=getX(chkIngameAllying)
$Y=getY(chkIngameAllying)+25
$Parent = ChkOptionsPanel
ToolTip=电脑多重工等于复制中心！
;Reversed=yes

[chkImmuneDerricks]
Text= 科技建筑无敌
CustomIniPath=INI/Game Options/科技建筑无敌.ini
Checked=True
$X=getX(chkStolenTech)
$Y=getY(chkStolenTech)+25
$Parent = ChkOptionsPanel
ToolTip= 科技建筑无法被摧毁
;Reversed=yes

[chkAILimit]
Text=AI超武限制
CustomIniPath=INI\Game Options\AILimit.ini
Checked=False
$X=getX(chkImmuneDerricks)
$Y=getY(chkImmuneDerricks)+25
$Parent = ChkOptionsPanel
ToolTip=不让AI造超武

;============================
; 2 Column of Checkboxes
;============================

[chkDestroyableBridges]
Text=桥梁可破坏
CustomIniPath=INI/Game Options/DestroyableBridges.ini
Checked=True
$X=getX(chkShortGame) + 130
$Y=getY(chkShortGame)
$Parent = ChkOptionsPanel
ToolTip=桥梁可以被推毁或修复！
Reversed=yes

[chkNoSpawnPreview]
Text= 载入图无位置
CustomIniPath=INI/Game Options/NoSpawnPreview.ini
Checked=False
$X=getX(chkDestroyableBridges)
$Y=getY(chkDestroyableBridges) + 25
$Parent = ChkOptionsPanel
ToolTip=载入界面不显示玩家位置！

[chkSatellite];免费全图视野
Text=免费全图视野
CustomIniPath=INI/Game Options/Satellite.ini
Checked=False
$X=getX(chkNoSpawnPreview)
$Y=getY(chkNoSpawnPreview) + 25
$Parent = ChkOptionsPanel
ToolTip = 免费全图视野！

[chkFreeRadar]
Text = 全图雷达
SpawnIniOption=FreeRadar
CustomIniPath=INI\Game Options\Free Radar.ini
Checked=False
$X=getX(chkSatellite)
$Y=getY(chkSatellite) + 25
$Parent = ChkOptionsPanel
ToolTip=小地图开启！

[chkConYardStart]
OptionName=ConYardStart
Text=建造厂开局
SpawnIniOption=ConYardStart
CustomIniPath=INI\Game Options\建造厂开局.ini
Checked=False
$X=getX(chkFreeRadar)
$Y=getY(chkFreeRadar) + 25
$Parent = ChkOptionsPanel
ToolTip=开启后，玩家进入游戏可直接拥有展开基地！

[chkMutiFactory]
OptionName=ConYard Start
Text= 多工厂加速
SpawnIniOption=ConYardStart
CustomIniPath=INI\Game Options\多工厂加速.ini
Checked=False
$X=getX(chkConYardStart)
$Y=getY(chkConYardStart) + 25
$Parent = ChkOptionsPanel
ToolTip= 提升多个工厂的建造速度！

[chkAutoRepair];自动维修
Text= 自动维修
CustomIniPath=INI\Game Options\Auto Repair.ini
Checked=False
$X=getX(chkMutiFactory)
$Y=getY(chkMutiFactory) + 25
$Parent = ChkOptionsPanel
ToolTip=开启后，建筑可自动修理！

[chkFogOfWar];可扩散战争迷雾
Text=可扩散迷雾
CustomIniPath=INI\Game Options\Fog.ini
Checked=False
$X=getX(chkAutoRepair)
$Y=getY(chkAutoRepair) + 25
$Parent = ChkOptionsPanel
ToolTip=开启后，战争迷雾将重新覆盖在已探测的区域！
ControlName = chkSatellite
ControlIndex = 0

[chkHugeWealthy]
Text = 疯狂矿石精炼
CustomIniPath=INI\Game Options\hugewealthy.ini  ;使用的ini
Checked=False	;默认不勾选
$X=getX(chkFogOfWar)
$Y=getY(chkFogOfWar) + 25
$Parent = ChkOptionsPanel
ToolTip=拥有的建筑越多，采矿的效率就越高，你就越富有！

[chkTech]
Text=开发者模式;
CustomIniPath=INI\Game Options\Tech.ini  ;使用的ini
Checked=False	;默认不勾选
$X=getX(chkHugeWealthy)
$Y=getY(chkHugeWealthy) +25 
$Parent = ChkOptionsPanel
ToolTip= 科技全开，快速建造，全图建造
ControlName = cmbStartingUnits,chkTech2
ControlIndex = 10,0

;============================
; 3 Column of Checkboxes
;============================

[chkTech2]
Text=科技全开
CustomIniPath=INI\Game Options\Tech2.ini
Checked=False
$X=getX(chkDestroyableBridges) + 130
$Y=getY(chkDestroyableBridges)
$Parent = ChkOptionsPanel
ToolTip=开局即可拥有所有科技！
ControlName = chkTech
ControlIndex = 0

[chkBuildLimit]
Text=限造解除
CustomIniPath=INI\Game Options\BuildLimit.ini
Checked=False
$X=getX(chkTech2)
$Y=getY(chkTech2)+25
$Parent = ChkOptionsPanel
ToolTip=限造为1的单位和建筑不再限制！

[chkCrazyBox]
Text=疯狂箱子
Checked=False
CustomIniPath=INI\Game Options\CrazyBox.ini
$X=getX(chkTech2)
$Y=getY(chkTech2)+50
$Parent = ChkOptionsPanel
ToolTip=对局刷新大量箱子

[chkStrenghBuild]
Text=铜墙铁壁
Checked=False
CustomIniPath=INI\Game Options\StrenghBuild.ini
$X=getX(chkCrazyBox)
$Y=getY(chkTech2)+75
$Parent = ChkOptionsPanel
ToolTip=大幅增加建筑血量

[chkBountyHunter]
Text=赏金猎人
Checked=False
$X=getX(chkStrenghBuild)
$Y=getY(chkTech2)+100
$Parent = ChkOptionsPanel
CustomIniPath=INI\Game Options\bounty.ini
ToolTip=击杀单位可获得不同比例赏金

[chkReturnBuilding]
Text=建筑归还
Checked=False
$X=getX(chkBountyHunter)
$Y=getY(chkBountyHunter)+25
$Parent = ChkOptionsPanel
CustomIniPath=INI\Game Options\ReturnBuilding.ini
ToolTip=敌军死亡后被占领建筑回归中立

[chkRemoveRubble]
Text=清除废墟
Checked=False
$X=getX(chkReturnBuilding)
$Y=getY(chkReturnBuilding)+25
$Parent = ChkOptionsPanel
CustomIniPath=INI\Game Options\RemoveRubble.ini
ToolTip=清除废墟，使得能够在其场地上新建建筑

[chkDefenceAiTrigger]
Text=禁用原生AI
Checked=False
CustomIniPath=INI\Game Options\DefenceAiTrigger.ini
$X=getX(chkRemoveRubble)
$Y=getY(chkRemoveRubble)+25
$Parent = ChkOptionsPanel
ToolTip=禁用原生AI

; Window Border Sides

[panelBorderTop]
Location=0,-8
BackgroundTexture=border-top.png
DrawMode=Stretched
Size=0,9
FillWidth=0

[panelBorderBottom]
Location=0,999
BackgroundTexture=border-bottom.png
DrawMode=Stretched
Size=0,9
FillWidth=0
DistanceFromBottomBorder=-8

[panelBorderLeft]
Location=-8,0
BackgroundTexture=border-left.png
DrawMode=Stretched
Size=9,0
FillHeight=0

[panelBorderRight]
Location=999,0
BackgroundTexture=border-right.png
DrawMode=Stretched
Size=9,0
FillHeight=0
DistanceFromRightBorder=-8

; Window Border Corners

[panelBorderCornerTL]
Location=-8,-8
BackgroundTexture=border-corner-tl.png
Size=9,9

[panelBorderCornerTR]
Location=999,-8
BackgroundTexture=border-corner-tr.png
Size=9,9
DistanceFromRightBorder=-8

[panelBorderCornerBL]
Location=-8,999
BackgroundTexture=border-corner-bl.png
Size=9,9
DistanceFromBottomBorder=-8

[panelBorderCornerBR]
Location=999,999
BackgroundTexture=border-corner-br.png
Size=9,9
DistanceFromRightBorder=-8
DistanceFromRightBorder=-8
DistanceFromBottomBorder=-8