using Rampastring.Tools;
using System.Collections.Generic;
using System.IO;

namespace ClientCore.INIProcessing
{
    /// <summary>
    /// 预处理 INI 文件。
    /// 允许节继承其他节。
    /// </summary>
    public class IniPreprocessor
    {
        public void ProcessIni(string sourceIniPath, string destinationIniPath)
        {
            File.Delete(destinationIniPath);

            if (!File.Exists(sourceIniPath))
                return;

            var iniFile = new IniFile(sourceIniPath);
            List<string> sections = iniFile.GetSections();
            sections.ForEach(sectionName => ProcessSection(iniFile, sectionName));
            iniFile.Comment = $"generated by DTA CnCNet client, see /Base/{Path.GetFileName(sourceIniPath)} for the original";

            iniFile.WriteIniFile(destinationIniPath);
        }

        /// <summary>
        /// 处理一个 INI 节并应用其可能的基础节。
        /// 返回该 INI 节。递归执行。
        /// </summary>
        /// <param name="iniFile">INI 文件。</param>
        /// <param name="sectionName">要处理的节名称。</param>
        private IniSection ProcessSection(IniFile iniFile, string sectionName)
        {
            IniSection section = iniFile.GetSection(sectionName);
            if (section == null)
                return null;

            string baseSectionName = section.GetStringValue("BaseSection", string.Empty);
            if (string.IsNullOrWhiteSpace(baseSectionName))
                return section;

            IniSection baseSection = ProcessSection(iniFile, baseSectionName);
            if (baseSection == null)
                return section;

            foreach (var kvp in baseSection.Keys)
            {
                if (!section.KeyExists(kvp.Key))
                    section.AddKey(kvp.Key, kvp.Value);
            }

            return section;
        }
    }
}
